services:
  backend:
    image: palashgupta94/backend:v1.0.0
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend/data:/data
    ports:
      - "5000:5000"
    networks:
      - my_fullstack_app_app-network

  frontend:
    image: palashgupta94/frontend:v1.0.0
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - my_fullstack_app_app-network

networks:
 my_fullstack_app_app-network:
    external: true
